function [barycenterX, barycenterY] = barycenter2D(x,y,C)
%% BARYCENTER2D returns x and y barycenter values of density map C
%  Assumption: Input coordinated x and y are evenly spaced!
%
%  The same input as for imagesc(x,y,C) can be used.
%
%   INPUT (from Matlab(R))
%     x    ... vector of length n, x-coordinates of image
%     y    ... vector of length m, y-coordinates of image
%     C    ... matrix of size n x m, density value for each coordiante
%
%   OUTPUT
%     barycenterX  ... double, x-coordinate value of the barycenter
%     barycenterY  ... double, y-coordinate value of the barycenter
%
%   CREDIT
%   [1] Andrei Bobrov https://www.mathworks.com/matlabcentral/answers/
%                     363181-center-of-mass-and-total-mass-of-a-matrix
%   [2] Matt J(faster)https://www.mathworks.com/matlabcentral/answers/
%                     133395-compute-centroid-of-a-matrix
%
%  TEST Examples (uncomment the parts below and at the end and run cell)
%{
T{1} = [...
    4 1 1 1 1;...
    1 2 2 2 1;...
    1 2 3 7 1;...
    1 9 4 2 1;...
    1 2 5 2 1;...
    1 2 4 9 1;...
    1 7 3 2 1;...
    1 2 2 2 1;...
    1 1 1 1 4;...
    ];
T{2} = [...
    0 0 0 0 0;...
    1 0 0 0 0;...
    1 1 0 0 0;...
    1 1 1 0 0;...
    1 1 1 1 0;...
    ];
T{3} = [...
    0 0 0 0 0;...
    0 0 0 0 0;...
    0 0 0 0 0;...
    1 1 0 0 0;...
    1 1 0 0 0;...
    ];
T{4} = [...
    5 0 0 0 3;...
    0 1 1 1 0;...
    0 1 0 1 0;...
    0 1 0 1 0;...
    0 0 0 0 0;...
    0 0 0 0 0;...
    0 0 1 0 0;...
    0 0 1 0 0;...
    0 1 1 1 0;...
    3 0 0 0 5;...
    ];
T{5} = ones([80,140]);
T{6} = zeros(10);

C = T{1}; % select an example
x = 1:size(C,2);
y = 1:size(C,1);
x = x + 123; % shift x vector to show correct x transformation
y = y + 456; % shift y vector to show correct y transformation
%}
% (c) Assembled and tranformation by H. Penasso Feb/15/2020
%

% Method 1:
%{
    tic
    C = C/sum(C(:));
    [m,n]=size(C);
    [I,J]=ndgrid(1:m,1:n);
    barycenterIdxX = dot(J(:),C(:));
    barycenterIdxY = dot(I(:),C(:));
    toc
%}
% Method 2:
% {
    tic
    tot_mass = sum(C(:));
    [ii,jj] = ndgrid(1:size(C,1),1:size(C,2));
    barycenterIdxX = sum(jj(:).*C(:))/tot_mass;
    barycenterIdxY = sum(ii(:).*C(:))/tot_mass;
    toc
%}
% Align barycenter indices and coordinate values
% Index vectors corresponding to the previous results
    xIdx = 1:size(C,2); % x axis index vector
    yIdx = 1:size(C,1); % y axis index vector
% X: linear fit between x-index vector and x coordinate vector
    slopeX      = sum((xIdx-mean(xIdx)).*(x-mean(x)))./...
                  sum((xIdx-mean(xIdx)).^2); % slope
    interceptX  = mean(x)-slopeX*mean(xIdx); % intercept
  % evaluate barycenter x value using slope and intercept of fit in x:
    barycenterX = slopeX*barycenterIdxX+interceptX;
% Y: linear fit between y-index vector and y coordinate vector
    slopeY      = sum((yIdx-mean(yIdx)).*(y-mean(y)))./...
                  sum((yIdx-mean(yIdx)).^2); % slope
    interceptY  = mean(y)-slopeY*mean(yIdx); % intercept
  % evaluate barycenter y value using slope and intercept of fit in y:
    barycenterY = slopeY*barycenterIdxY+interceptY;
%{
% Plot for test example
    imagesc(x,y,C)
    hold on
    plot(barycenterX,barycenterY,'wx',...
         barycenterX,barycenterY,'wo','MarkerSize',20,'LineWidth',2)
%}